<?php
namespace src\product;
abstract class book extends product
{
    private float $weight;

    public function getWeight(): float
    {
        return $this->weight;
    }

    public function setWeight(float $weight): void
    {
        $this->weight = $weight;
    }

    protected function saveProduct($productData)
    {
        parent::saveProduct($productData); // TODO: Change the autogenerated stub
    }
}
