<?php
namespace src\product;
abstract class Book extends product
{
    private float $weight;

    public function __construct($data)
    {
        parent::__construct($data);
        $this->weight = $data["price"];
    }

    public function getWeight(): float
    {
        return $this->weight;
    }

    public function setWeight(float $weight): void
    {
        $this->weight = $weight;
    }

    protected function saveProduct($productData)
    {
        parent::saveProduct($productData); // TODO: Change the autogenerated stub
    }
    protected abstract function jsonSerialize();
}
